<a href="https://colab.research.google.com/github/MiguelLuan/AluraStore/blob/main/AluraStore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
url1 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_1.csv'
url2 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_2.csv'
url3 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_3.csv'
url4 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_4.csv'

In [5]:
loja1,loja2,loja3,loja4 = [pd.read_csv(url) for url in [url1,url2,url3,url4]]

# 1. Informações Gerais das Lojas

## Loja 1

In [7]:
# Informações estruturais da dataframe
loja1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [23]:
# Dados das 5 primeiras linhas
loja1.head()

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon
0,Assistente virtual,eletronicos,219.08,9.249790,16/01/2021,Pedro Gomes,SP,4,cartao_credito,8,-22.19,-48.79
1,Mesa de jantar,moveis,256.35,11.234305,18/05/2022,Beatriz Moraes,RJ,1,cartao_credito,4,-22.25,-42.66
2,Jogo de tabuleiro,brinquedos,279.51,21.262681,15/03/2021,João Souza,DF,1,cartao_credito,1,-15.83,-47.86
3,Micro-ondas,eletrodomesticos,1009.99,54.667344,03/05/2022,João Souza,RS,4,boleto,1,-30.17,-53.50
4,Cadeira de escritório,moveis,446.99,26.964689,07/11/2020,Larissa Alves,MG,5,boleto,1,-18.10,-44.38

In [33]:
vlr_produtos_lj1 = loja1['Produto'].unique()
vlr_categoria_lj1 = loja1['Categoria do Produto'].unique()
vlr_tipo_pg_lj1 = loja1['Tipo de pagamento'].unique()
vlr_vendedor_lj1 = loja1['Vendedor'].unique()
vlr_local_lj1 = loja1['Local da compra'].unique()

print(f'Produtos: {vlr_produtos_lj1}\n')
print(f'Categoria: {vlr_categoria_lj1}\n')
print(f'Tipo de Pagamento: {vlr_tipo_pg_lj1}\n')
print(f'Vendedor: {vlr_vendedor_lj1}\n')
print(f'Local: {vlr_local_lj1}')

Produtos: ['Assistente virtual' 'Mesa de jantar' 'Jogo de tabuleiro' 'Micro-ondas'
 'Cadeira de escritório' 'Blocos de montar' 'Boneca bebê' 'Lava louças'
 'Lavadora de roupas' 'Carrinho controle remoto' 'Geladeira'
 'Fone de ouvido' 'Panela de pressão' 'Bicicleta'
 'Ciência de dados com python' 'Bola de vôlei' 'Xadrez de madeira'
 'TV Led UHD 4K' 'Copo térmico' 'Kit banquetas' 'Dashboards com Power BI'
 'Faqueiro' 'Jogo de panelas' 'Bateria' 'Corda de pular' 'Fogão'
 'Cama box' 'Impressora' 'Cômoda' 'Guarda roupas' 'Dinossauro Rex'
 'Guitarra' 'Secadora de roupas' 'Sofá retrátil' 'Tablet ABXY'
 'Cubo mágico 8x8' 'Jogo de copos' 'Modelagem preditiva'
 'Celular Plus X42' 'Mochila' 'Bola de basquete' 'Headset' 'Poltrona'
 'Violão' 'Iniciando em programação' 'Celular ABXY' 'Smartwatch'
 'Mesa de centro' 'Cama king' 'Smart TV' 'Pandeiro']

Categoria: ['eletronicos' 'moveis' 'brinquedos' 'eletrodomesticos'
 'utilidades domesticas' 'esporte e lazer' 'livros'
 'instrumentos musicais']

Tipo de Pagamento: ['cartao_credito' 'boleto' 'cupom' 'cartao_debito']

Vendedor: ['Pedro Gomes' 'Beatriz Moraes' 'João Souza' 'Larissa Alves'
 'Felipe Santos' 'Thiago Silva' 'Bianca Santos' 'Rafael Costa'
 'Camila Ribeiro' 'Juliana Costa' 'Bruno Rodrigues' 'Mariana Ferreira'
 'Lucas Oliveira' 'Isabella Pereira']

Local: ['SP' 'RJ' 'DF' 'RS' 'MG' 'CE' 'ES' 'BA' 'TO' 'PR' 'AP' 'GO' 'AL' 'PI'
 'PE' 'AM' 'RN' 'PA' 'PB' 'SC' 'SE' 'MT' 'MS' 'RO' 'MA' 'AC']

## Loja 2

In [8]:
## Informações estruturais da dataframe
loja2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

## Loja 3

In [15]:
# Informações estruturais da dataframe
loja3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

## Loja 4

In [16]:
# Informações estruturais da dataframe
loja4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2358 entries, 0 to 2357
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2358 non-null   object
 1   Categoria do Produto    2358 non-null   object
 2   Preço                   2358 non-null   float64
 3   Frete                   2358 non-null   float64
 4   Data da Compra          2358 non-null   object
 5   Vendedor                2358 non-null   object
 6   Local da compra         2358 non-null   object
 7   Avaliação da compra     2358 non-null   int64
 8   Tipo de pagamento       2358 non-null   object
 9   Quantidade de parcelas  2358 non-null   int64
 10  lat                     2358 non-null   float64
 11  lon                     2358 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.2+ KB

# 2. Análise do Faturamento

In [38]:
faturamento_loja1 = (loja1['Preço'] + loja1['Frete']).sum()
faturamento_loja1

np.float64(1616347.0877956916)

In [36]:
faturamento_loja2 = (loja2['Preço'] + loja2['Frete']).sum()
faturamento_loja2

np.float64(1616347.0877956916)

In [39]:
faturamento_loja3 = (loja3['Preço'] + loja3['Frete']).sum()
faturamento_loja3

np.float64(1542047.691222643)

In [40]:
faturamento_loja4 = (loja4['Preço'] + loja4['Frete']).sum()
faturamento_loja4

np.float64(1458253.455118983)

# 3. Vendas Por Categoria

In [55]:
qtd_produtos_loja1 = loja1.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja1['Faturamento'] = qtd_produtos_loja1['Preco_Total'] + qtd_produtos_loja1['Frete_Total']

qtd_produtos_loja1.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja1

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                324   25299.265959
eletrodomesticos                          312  510678.320571
eletronicos                               448  603278.238660
esporte e lazer                           284   55216.657567
instrumentos musicais                     182  128243.495861
livros                                    173   12336.410244
moveis                                    465  263505.317336
utilidades domesticas                     171   17789.381598

In [56]:
qtd_produtos_loja2 = loja2.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja2['Faturamento'] = qtd_produtos_loja2['Preco_Total'] + qtd_produtos_loja2['Frete_Total']

qtd_produtos_loja2.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja2

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                313   22445.828832
eletrodomesticos                          305  489499.129045
eletronicos                               422  576858.274761
esporte e lazer                           275   48828.896941
instrumentos musicais                     224  147397.090812
livros                                    197   14195.836448
moveis                                    442  247817.049515
utilidades domesticas                     181   20731.111659

In [57]:
qtd_produtos_loja3 = loja3.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja3['Faturamento'] = qtd_produtos_loja3['Preco_Total'] + qtd_produtos_loja3['Frete_Total']

qtd_produtos_loja3.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja3

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                315   27258.598348
eletrodomesticos                          278  462310.463552
eletronicos                               451  576840.388656
esporte e lazer                           277   50020.617735
instrumentos musicais                     177  108652.544679
livros                                    185   13326.377563
moveis                                    499  282475.234825
utilidades domesticas                     177   21163.465865

In [58]:
qtd_produtos_loja4 = loja1.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja4['Faturamento'] = qtd_produtos_loja4['Preco_Total'] + qtd_produtos_loja4['Frete_Total']

qtd_produtos_loja4.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja4

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                324   25299.265959
eletrodomesticos                          312  510678.320571
eletronicos                               448  603278.238660
esporte e lazer                           284   55216.657567
instrumentos musicais                     182  128243.495861
livros                                    173   12336.410244
moveis                                    465  263505.317336
utilidades domesticas                     171   17789.381598

# 4. Média de Avaliação das Lojas

# 5. Produtos Mais e Menos Vendidos

# 6. Frete Médio por Loja