<a href="https://colab.research.google.com/github/MiguelLuan/AluraStore/blob/main/AluraStore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

In [22]:
url1 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_1.csv'
url2 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_2.csv'
url3 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_3.csv'
url4 = 'https://raw.githubusercontent.com/MiguelLuan/AluraStore/main/data-base/loja_4.csv'

In [23]:
loja1,loja2,loja3,loja4 = [pd.read_csv(url) for url in [url1,url2,url3,url4]]

# 1. Informações Gerais das Lojas

## Loja 1

In [24]:
# Informações estruturais da dataframe
loja1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [25]:
# Dados das 5 primeiras linhas
loja1.head()

,Produto,Categoria do Produto,Preço,Frete,Data da Compra,Vendedor,Local da compra,Avaliação da compra,Tipo de pagamento,Quantidade de parcelas,lat,lon
0,Assistente virtual,eletronicos,219.08,9.249790,16/01/2021,Pedro Gomes,SP,4,cartao_credito,8,-22.19,-48.79
1,Mesa de jantar,moveis,256.35,11.234305,18/05/2022,Beatriz Moraes,RJ,1,cartao_credito,4,-22.25,-42.66
2,Jogo de tabuleiro,brinquedos,279.51,21.262681,15/03/2021,João Souza,DF,1,cartao_credito,1,-15.83,-47.86
3,Micro-ondas,eletrodomesticos,1009.99,54.667344,03/05/2022,João Souza,RS,4,boleto,1,-30.17,-53.50
4,Cadeira de escritório,moveis,446.99,26.964689,07/11/2020,Larissa Alves,MG,5,boleto,1,-18.10,-44.38

In [26]:
#Possíveis valores de determinadas colunas:

vlr_produtos_lj1 = loja1['Produto'].unique()
vlr_categoria_lj1 = loja1['Categoria do Produto'].unique()
vlr_tipo_pg_lj1 = loja1['Tipo de pagamento'].unique()
vlr_vendedor_lj1 = loja1['Vendedor'].unique()
vlr_local_lj1 = loja1['Local da compra'].unique()

print(f'Produtos: {vlr_produtos_lj1}\n')
print(f'Categoria: {vlr_categoria_lj1}\n')
print(f'Tipo de Pagamento: {vlr_tipo_pg_lj1}\n')
print(f'Vendedor: {vlr_vendedor_lj1}\n')
print(f'Local: {vlr_local_lj1}')

Produtos: ['Assistente virtual' 'Mesa de jantar' 'Jogo de tabuleiro' 'Micro-ondas'
 'Cadeira de escritório' 'Blocos de montar' 'Boneca bebê' 'Lava louças'
 'Lavadora de roupas' 'Carrinho controle remoto' 'Geladeira'
 'Fone de ouvido' 'Panela de pressão' 'Bicicleta'
 'Ciência de dados com python' 'Bola de vôlei' 'Xadrez de madeira'
 'TV Led UHD 4K' 'Copo térmico' 'Kit banquetas' 'Dashboards com Power BI'
 'Faqueiro' 'Jogo de panelas' 'Bateria' 'Corda de pular' 'Fogão'
 'Cama box' 'Impressora' 'Cômoda' 'Guarda roupas' 'Dinossauro Rex'
 'Guitarra' 'Secadora de roupas' 'Sofá retrátil' 'Tablet ABXY'
 'Cubo mágico 8x8' 'Jogo de copos' 'Modelagem preditiva'
 'Celular Plus X42' 'Mochila' 'Bola de basquete' 'Headset' 'Poltrona'
 'Violão' 'Iniciando em programação' 'Celular ABXY' 'Smartwatch'
 'Mesa de centro' 'Cama king' 'Smart TV' 'Pandeiro']

Categoria: ['eletronicos' 'moveis' 'brinquedos' 'eletrodomesticos'
 'utilidades domesticas' 'esporte e lazer' 'livros'
 'instrumentos musicais']

Tipo de Pagamento: ['cartao_credito' 'boleto' 'cupom' 'cartao_debito']

Vendedor: ['Pedro Gomes' 'Beatriz Moraes' 'João Souza' 'Larissa Alves'
 'Felipe Santos' 'Thiago Silva' 'Bianca Santos' 'Rafael Costa'
 'Camila Ribeiro' 'Juliana Costa' 'Bruno Rodrigues' 'Mariana Ferreira'
 'Lucas Oliveira' 'Isabella Pereira']

Local: ['SP' 'RJ' 'DF' 'RS' 'MG' 'CE' 'ES' 'BA' 'TO' 'PR' 'AP' 'GO' 'AL' 'PI'
 'PE' 'AM' 'RN' 'PA' 'PB' 'SC' 'SE' 'MT' 'MS' 'RO' 'MA' 'AC']

## Loja 2

In [27]:
## Informações estruturais da dataframe
loja2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

## Loja 3

In [28]:
# Informações estruturais da dataframe
loja3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2359 non-null   object
 1   Categoria do Produto    2359 non-null   object
 2   Preço                   2359 non-null   float64
 3   Frete                   2359 non-null   float64
 4   Data da Compra          2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Local da compra         2359 non-null   object
 7   Avaliação da compra     2359 non-null   int64
 8   Tipo de pagamento       2359 non-null   object
 9   Quantidade de parcelas  2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

## Loja 4

In [29]:
# Informações estruturais da dataframe
loja4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2358 entries, 0 to 2357
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Produto                 2358 non-null   object
 1   Categoria do Produto    2358 non-null   object
 2   Preço                   2358 non-null   float64
 3   Frete                   2358 non-null   float64
 4   Data da Compra          2358 non-null   object
 5   Vendedor                2358 non-null   object
 6   Local da compra         2358 non-null   object
 7   Avaliação da compra     2358 non-null   int64
 8   Tipo de pagamento       2358 non-null   object
 9   Quantidade de parcelas  2358 non-null   int64
 10  lat                     2358 non-null   float64
 11  lon                     2358 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.2+ KB

# 2. Análise do Faturamento

In [30]:
faturamento_loja1 = (loja1['Preço'] + loja1['Frete']).sum()
faturamento_loja1

np.float64(1616347.0877956916)

In [31]:
faturamento_loja2 = (loja2['Preço'] + loja2['Frete']).sum()
faturamento_loja2

np.float64(1567773.218012645)

In [32]:
faturamento_loja3 = (loja3['Preço'] + loja3['Frete']).sum()
faturamento_loja3

np.float64(1542047.691222643)

In [33]:
faturamento_loja4 = (loja4['Preço'] + loja4['Frete']).sum()
faturamento_loja4

np.float64(1458253.455118983)

# 3. Vendas Por Categoria

In [34]:
# Quantidade de produtos vendidos junto ao faturamento da loja1
qtd_produtos_loja1 = loja1.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja1['Faturamento'] = qtd_produtos_loja1['Preco_Total'] + qtd_produtos_loja1['Frete_Total']

qtd_produtos_loja1.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja1

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                324   25299.265959
eletrodomesticos                          312  510678.320571
eletronicos                               448  603278.238660
esporte e lazer                           284   55216.657567
instrumentos musicais                     182  128243.495861
livros                                    173   12336.410244
moveis                                    465  263505.317336
utilidades domesticas                     171   17789.381598

In [35]:
# Quantidade de produtos vendidos junto ao faturamento da loja2
qtd_produtos_loja2 = loja2.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja2['Faturamento'] = qtd_produtos_loja2['Preco_Total'] + qtd_produtos_loja2['Frete_Total']

qtd_produtos_loja2.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja2

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                313   22445.828832
eletrodomesticos                          305  489499.129045
eletronicos                               422  576858.274761
esporte e lazer                           275   48828.896941
instrumentos musicais                     224  147397.090812
livros                                    197   14195.836448
moveis                                    442  247817.049515
utilidades domesticas                     181   20731.111659

In [36]:
# Quantidade de produtos vendidos junto ao faturamento da loja3
qtd_produtos_loja3 = loja3.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja3['Faturamento'] = qtd_produtos_loja3['Preco_Total'] + qtd_produtos_loja3['Frete_Total']

qtd_produtos_loja3.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja3

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                315   27258.598348
eletrodomesticos                          278  462310.463552
eletronicos                               451  576840.388656
esporte e lazer                           277   50020.617735
instrumentos musicais                     177  108652.544679
livros                                    185   13326.377563
moveis                                    499  282475.234825
utilidades domesticas                     177   21163.465865

In [37]:
# Quantidade de produtos vendidos junto ao faturamento da loja4
qtd_produtos_loja4 = loja1.groupby('Categoria do Produto').agg(
    Quantidade_de_Produtos = ('Categoria do Produto','size'),
    Preco_Total = ('Preço','sum'),
    Frete_Total = ('Frete','sum'),
)

qtd_produtos_loja4['Faturamento'] = qtd_produtos_loja4['Preco_Total'] + qtd_produtos_loja4['Frete_Total']

qtd_produtos_loja4.drop(columns=['Preco_Total','Frete_Total'],inplace=True)

qtd_produtos_loja4

                       Quantidade_de_Produtos    Faturamento
Categoria do Produto
brinquedos                                324   25299.265959
eletrodomesticos                          312  510678.320571
eletronicos                               448  603278.238660
esporte e lazer                           284   55216.657567
instrumentos musicais                     182  128243.495861
livros                                    173   12336.410244
moveis                                    465  263505.317336
utilidades domesticas                     171   17789.381598

# 4. Média de Avaliação das Lojas

In [38]:
#Média de avaliação dos clientes da loja1
loja1['Avaliação da compra'].mean()

np.float64(3.976685036032217)

In [41]:
#Média da avaliação dos clientes da loja1 por produto
avaliacao_categoria_loja1 = loja1.groupby('Categoria do Produto')['Avaliação da compra'].mean().sort_values(ascending=False)
avaliacao_categoria_loja1

Categoria do Produto
brinquedos               4.077160
instrumentos musicais    4.049451
eletrodomesticos         4.032051
eletronicos              4.004464
livros                   3.976879
moveis                   3.946237
esporte e lazer          3.897887
utilidades domesticas    3.748538
Name: Avaliação da compra, dtype: float64

In [42]:
#Média de avaliação dos clientes da loja2
loja2['Avaliação da compra'].mean()

np.float64(4.037303942348453)

In [44]:
#Média da avaliação dos clientes da loja2 por produto
avaliacao_categoria_loja2 = loja2.groupby('Categoria do Produto')['Avaliação da compra'].mean().sort_values(ascending=False)
avaliacao_categoria_loja2

Categoria do Produto
moveis                   4.092760
eletrodomesticos         4.072131
utilidades domesticas    4.071823
esporte e lazer          4.065455
instrumentos musicais    4.035714
brinquedos               4.025559
eletronicos              3.971564
livros                   3.949239
Name: Avaliação da compra, dtype: float64

In [47]:
#Média de avaliação dos clientes da loja3
loja3['Avaliação da compra'].mean()

np.float64(4.048325561678677)

In [45]:
#Média da avaliação dos clientes da loja3 por produto
avaliacao_categoria_loja3 = loja3.groupby('Categoria do Produto')['Avaliação da compra'].mean().sort_values(ascending=False)
avaliacao_categoria_loja3

Categoria do Produto
brinquedos               4.196825
moveis                   4.098196
utilidades domesticas    4.073446
livros                   4.048649
eletrodomesticos         4.010791
instrumentos musicais    4.005650
eletronicos              3.986696
esporte e lazer          3.938628
Name: Avaliação da compra, dtype: float64

In [48]:
#Média de avaliação dos clientes da loja4
loja4['Avaliação da compra'].mean()

np.float64(3.9957591178965224)

In [46]:
#Média da avaliação dos clientes da loja1 por produto
avaliacao_categoria_loja4 = loja4.groupby('Categoria do Produto')['Avaliação da compra'].mean().sort_values(ascending=False)
avaliacao_categoria_loja4

Categoria do Produto
esporte e lazer          4.054152
livros                   4.042781
utilidades domesticas    4.009950
eletronicos              4.006652
moveis                   3.997917
brinquedos               3.988166
eletrodomesticos         3.929134
instrumentos musicais    3.911765
Name: Avaliação da compra, dtype: float64

# 5. Produtos Mais e Menos Vendidos

In [66]:
#Produtos que forma os mais e menos vendidos da loja1
pdt_vdd_loja1 = loja1.groupby('Produto').size()
pdt_vdd_loja1.name = 'Quantidade_de_Produtos'

pdt_mais_vdd_loja1,pdt_menos_vdd_loja1 = pdt_vdd_loja1.idxmax(),pdt_vdd_loja1.idxmin()

print(f'Produto da loja1 mais vendido: {pdt_mais_vdd_loja1}')
print(f'Produto da loja1 menos vendido: {pdt_menos_vdd_loja1}')

Produto da loja1 mais vendido: Guarda roupas
Produto da loja1 menos vendido: Celular ABXY

In [67]:
#Produots que forma os mais e menos vendidos da loja2
pdt_vdd_loja2 = loja2.groupby('Produto').size()
pdt_vdd_loja2.name = 'Quantidade_de_Produtos'

pdt_mais_vdd_loja2,pdt_menos_vdd_loja2 = pdt_vdd_loja2.idxmax(),pdt_vdd_loja2.idxmin()

print(f'Produto da loja2 mais vendido: {pdt_mais_vdd_loja2}')
print(f'Produto da loja2 menos vendido: {pdt_menos_vdd_loja2}')

Produto da loja2 mais vendido: Iniciando em programação
Produto da loja2 menos vendido: Jogo de tabuleiro

In [68]:
#Produots que forma os mais e menos vendidos da loja3
pdt_vdd_loja3 = loja3.groupby('Produto').size()
pdt_vdd_loja3.name = 'Quantidade_de_Produtos'

pdt_mais_vdd_loja3,pdt_menos_vdd_loja3 = pdt_vdd_loja3.idxmax(),pdt_vdd_loja3.idxmin()

print(f'Produto da loja3 mais vendido: {pdt_mais_vdd_loja3}')
print(f'Produto da loja3 menos vendido: {pdt_menos_vdd_loja3}')

Produto da loja3 mais vendido: Kit banquetas
Produto da loja3 menos vendido: Blocos de montar

In [69]:
#Produots que forma os mais e menos vendidos da loja4
pdt_vdd_loja4 = loja4.groupby('Produto').size()
pdt_vdd_loja4.name = 'Quantidade_de_Produtos'

pdt_mais_vdd_loja4,pdt_menos_vdd_loja4 = pdt_vdd_loja4.idxmax(),pdt_vdd_loja4.idxmin()

print(f'Produto da loja4 mais vendido: {pdt_mais_vdd_loja4}')
print(f'Produto da loja4 menos vendido: {pdt_menos_vdd_loja4}')

Produto da loja4 mais vendido: Cama box
Produto da loja4 menos vendido: Guitarra

# 6. Frete Médio por Loja

In [71]:
#Frete médio da loja1
frete_medio_loja1 = loja1['Frete'].mean()
frete_medio_loja1

np.float64(34.69180491551149)

In [77]:
#Frete médio por estado e categoria de produto da loja1
frete_etd_cat_loja1 = loja1.groupby(['Local da compra','Categoria do Produto'])['Frete'].mean().sort_values(ascending=False)
frete_etd_cat_loja1.head(10)

Local da compra  Categoria do Produto
PI               eletrodomesticos        182.708323
RN               eletrodomesticos        126.208651
AC               eletrodomesticos        123.838510
PE               eletronicos             120.875519
RO               eletronicos             120.258308
PB               eletrodomesticos        103.046185
SC               eletrodomesticos        102.141860
GO               eletronicos             100.081792
PR               eletrodomesticos         96.380061
PB               eletronicos              94.061364
Name: Frete, dtype: float64

In [79]:
#Frete médio por estado e categoria de produto da loja1
frete_etd_cat_loja1.tail(10)

Local da compra  Categoria do Produto
RO               esporte e lazer          1.855433
PB               brinquedos               1.791461
PR               livros                   1.684736
SE               livros                   1.551340
PI               instrumentos musicais    1.409170
SE               esporte e lazer          1.109922
GO               brinquedos               1.106227
TO               brinquedos               0.682157
BA               brinquedos               0.614136
MT               utilidades domesticas    0.000000
Name: Frete, dtype: float64

In [72]:
#Frete médio da loja2
frete_medio_loja2 = loja2['Frete'].mean()
frete_medio_loja2

np.float64(33.62194065817927)

In [80]:
#Frete médio por estado e categoria de produto da loja2
frete_etd_cat_loja2 = loja2.groupby(['Local da compra','Categoria do Produto'])['Frete'].mean().sort_values(ascending=False)
frete_etd_cat_loja2.head(10)

Local da compra  Categoria do Produto
RR               eletronicos             169.541339
TO               eletrodomesticos        110.573490
RO               eletronicos             109.392449
SE               eletronicos             107.527256
PB               eletrodomesticos        107.043724
PI               eletronicos             102.931151
MS               eletrodomesticos         96.974996
MA               eletrodomesticos         94.265268
RJ               eletrodomesticos         90.694230
RN               eletronicos              89.196061
Name: Frete, dtype: float64

In [81]:
#Frete médio por estado e categoria de produto da loja2
frete_etd_cat_loja2.tail(10)

Local da compra  Categoria do Produto
ES               brinquedos               1.395808
PA               brinquedos               1.288284
AL               esporte e lazer          1.269802
MA               esporte e lazer          1.159708
AL               livros                   1.049093
ES               livros                   0.977742
AM               brinquedos               0.000000
MS               utilidades domesticas    0.000000
PB               esporte e lazer          0.000000
RN               esporte e lazer          0.000000
Name: Frete, dtype: float64

In [73]:
#Frete médio da loja3
frete_medio_loja3 = loja3['Frete'].mean()
frete_medio_loja3

np.float64(33.07446427411743)

In [82]:
#Frete médio por estado e categoria de produto da loja3
frete_etd_cat_loja3 = loja3.groupby(['Local da compra','Categoria do Produto'])['Frete'].mean().sort_values(ascending=False)
frete_etd_cat_loja3.head(10)

Local da compra  Categoria do Produto
SE               eletronicos             111.388436
SC               eletrodomesticos        107.540258
AL               eletrodomesticos        104.348874
ES               eletrodomesticos        100.647497
PR               eletrodomesticos         98.403449
PE               eletrodomesticos         94.701848
GO               eletronicos              93.824273
RJ               eletrodomesticos         92.578983
ES               eletronicos              92.497758
AM               eletrodomesticos         91.849066
Name: Frete, dtype: float64

In [83]:
#Frete médio por estado e categoria de produto da loja3
frete_etd_cat_loja3.tail(10)

Local da compra  Categoria do Produto
TO               brinquedos               2.166875
PE               livros                   2.082788
RS               livros                   2.041844
SC               brinquedos               1.958582
MA               livros                   1.911656
PA               utilidades domesticas    1.838349
DF               utilidades domesticas    1.318964
AM               utilidades domesticas    0.000000
PI               brinquedos               0.000000
SE               brinquedos               0.000000
Name: Frete, dtype: float64

In [74]:
#Frete médio da loja4
frete_medio_loja4 = loja4['Frete'].mean()
frete_medio_loja4

np.float64(31.278997081841727)

In [84]:
#Frete médio por estado e categoria de produto da loja4
frete_etd_cat_loja4 = loja4.groupby(['Local da compra','Categoria do Produto'])['Frete'].mean().sort_values(ascending=False)
frete_etd_cat_loja4.head(10)

Local da compra  Categoria do Produto
PA               eletronicos             143.305718
MT               eletronicos             125.896130
MA               eletronicos             124.425064
RN               eletronicos             105.124357
RS               eletrodomesticos         98.325303
PE               eletronicos              90.180687
PB               eletrodomesticos         89.715313
RJ               eletrodomesticos         89.506133
MS               eletrodomesticos         88.698444
PA               eletrodomesticos         86.629360
Name: Frete, dtype: float64

In [85]:
#Frete médio por estado e categoria de produto da loja4
frete_etd_cat_loja4.head(10)

Local da compra  Categoria do Produto
PA               eletronicos             143.305718
MT               eletronicos             125.896130
MA               eletronicos             124.425064
RN               eletronicos             105.124357
RS               eletrodomesticos         98.325303
PE               eletronicos              90.180687
PB               eletrodomesticos         89.715313
RJ               eletrodomesticos         89.506133
MS               eletrodomesticos         88.698444
PA               eletrodomesticos         86.629360
Name: Frete, dtype: float64